/**
 * iOS apple-touch-startup-image entries (device-width / device-height / pixel-ratio).
 * Assets generated by `npm run pwa:assets` from public/brand/logo.png.
 */
export const appleStartupImages = [
  {
    url: "/splash/iphone-16-pro-max.png",
    media:
      "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-16-pro-max-landscape.png",
    media:
      "(device-width: 956px) and (device-height: 440px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-16-pro.png",
    media:
      "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-16-pro-landscape.png",
    media:
      "(device-width: 874px) and (device-height: 402px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-15-pro-max.png",
    media:
      "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-15-pro-max-landscape.png",
    media:
      "(device-width: 932px) and (device-height: 430px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-14-pro.png",
    media:
      "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-14-pro-landscape.png",
    media:
      "(device-width: 852px) and (device-height: 393px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-14.png",
    media:
      "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-14-landscape.png",
    media:
      "(device-width: 844px) and (device-height: 390px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-xr.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/iphone-xr-landscape.png",
    media:
      "(device-width: 896px) and (device-height: 414px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/iphone-8-plus.png",
    media:
      "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-8-plus-landscape.png",
    media:
      "(device-width: 736px) and (device-height: 414px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/splash/iphone-se.png",
    media:
      "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/iphone-se-landscape.png",
    media:
      "(device-width: 667px) and (device-height: 375px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/ipad-pro-12-9.png",
    media:
      "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/ipad-pro-12-9-landscape.png",
    media:
      "(device-width: 1366px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/ipad-pro-11.png",
    media:
      "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/ipad-pro-11-landscape.png",
    media:
      "(device-width: 1194px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/ipad-10-2.png",
    media:
      "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2)",
  },
  {
    url: "/splash/ipad-10-2-landscape.png",
    media:
      "(device-width: 1080px) and (device-height: 810px) and (-webkit-device-pixel-ratio: 2)",
  },
] as const;
